name = "sub" # todo
main = "js/_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true


[[routes]]
pattern = "ns1.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "server.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.server.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.server.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.server.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.server.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.server.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.server.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.server.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.server.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.server.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.server.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.server.ndeso.web.id"
custom_domain = true
