name = "link" # todo
main = "_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true


[[routes]]
pattern = "sub.bmkg.xyz"
custom_domain = true

